### ISSUE TITLE
[REQ] Component Request: SGP30 Air Quality Sensor Breakout

### ISSUE THREAD

**Issue by brentru** [adafruit/Wippersnapper_Components#102]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
The full name of the specific component.

**What type of component is this (i.e.: Pin, I2C)?**
Add any other context about the component request here.

**Product URL or Datasheet**
Add a link to the product's URL or datasheet here.

**Additional context**
Add any other context about the component request here.

**Comment by gbinco** [comment]
I would like to see the SGP30 added to Wippersnapper, thank you!!

**Comment by gbinco** [comment]
Is this still in the queue to be added?

**Comment by brentru** [comment]
@gbinco  Yes!

**Comment by tyeth** [comment]
I will be adding this over the next week as part of #129

**Comment by tyeth** [comment]
@gbinco please give it a try in the latest build!

**Comment by gbinco** [comment]
> @gbinco please give it a try in the latest build!
It works and it's beautiful! Thank you so much!! :)
