### ISSUE TITLE
[REQ] Component Request: Sensirion SEN55 Particulate / NOx / VOC / RHT Sensor unit

### ISSUE THREAD

**Issue by tyeth** [adafruit/Wippersnapper_Components#103]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
Sensirion SEN55

**What type of component is this (i.e.: Pin, I2C)?**
I2C

**Product URL or Datasheet**
https://sensirion.com/products/catalog/SEN55/

**Additional context**
I plan to add the SEN55, although depending on adafruits upcoming products it may be worth supporting lower models:
SEN50 (only particulate matter signals available)
SEN54 (no NOx signal available)
SEN55 (full feature set)

**Comment by tyeth** [comment]
I would love some advice on how best to handle the two gas values (Nitric/Nitrous Oxide, and VOCs/ethanol), which are indexes rather than unit based, but still very effective at showing change / events. I've initially stuck them in as the first two raw bytes for a raw event as I swear I read that was the thing to do somewhere sometime ago 🤞  No idea what I'll do with them from there but that's next weeks problem.
https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/compare/main...tyeth:Adafruit_Wippersnapper_Arduino:add-SEN55?diff=unified#diff-1b95044a0a20c33a93edf6a4bfb2fcce4ca8a791ca0862e09dc7acef46f53a1dR133

**Comment by brentru** [comment]
> which are indexes rather than unit based, but still very effective at showing change / events

Setting the readings as raw events is good, if they're unit-less. How many of these event types do you need to log?

**Comment by tyeth** [comment]
Just those two, nox/voc, although I did consider logging the particle counts (#/cm3) as raw or integers too, for now I'm happy with just the ug/m3 particle metrics.

**Comment by tyeth** [comment]
My biggest issue with raw is it needs demodulating somewhere. Fine for complex scenarios, not easily logged. I _ass_u_me_ the raw values aren't broken up and plotted separately in adafruit io?

**Comment by lorennorman** [comment]
Off the top of my head, I think I use a sensor's type as part of its unique ID, assuming no I2C device would have 2 sensors of the same type.

That assumption breaks down for unitless, I now see. I'll need to do some rethinking around this use case and get an enhancement in to support it.

**Comment by tyeth** [comment]
I had thought the displayname could be used to differentiate (after sanitizing - prefixed by type), so I would define two raw subComponent a bit like this one with voltage and unitless-percentage, but two raw types with vocIndex and noxIndex as displaynames. I would also include the usual suspects for particles+temp+humidity.
![Screenshot 2022-12-13 at 14 45 56](https://user-images.githubusercontent.com/6692083/207364938-ada29156-cba4-4de1-97e1-620ff661ddb6.png)
The displaynames can be supplied, which would mean one of each type if not changed, as they default to 
![Screenshot 2022-12-13 at 14 48 10](https://user-images.githubusercontent.com/6692083/207365290-f94f67d1-9876-4c76-a61c-32f53bee2b92.png)

Having looked at mqtt topic length on aws, 256bytes of utf8, I'm less confident in that idea working, maybe if there was a metricName property or something but that screws with the whole system.

**Comment by tyeth** [comment]
@lorennorman just spotted the subcomponents has a type as well as displayname, different to the other uses of type in the non-i2c schemas. Seems like no example of usage but exactly what we need https://github.com/adafruit/Wippersnapper_Components/blob/6a7d094661e889e7e3d9e719aae8b03f81d36b34/components/i2c/schema.json#L18

**Comment by brentru** [comment]
@tyeth  Could we instead add `nox` and `voc` as sensor unit types. These would be unitless, so `nox-index` and `voc-index` would be the sensor unit type names?

**Comment by tyeth** [comment]
@brentru Yeah sure, much easier win before Christmas. Desperate to get my burnt-toast detector running as my burn rate is >70%🧯 broken dial... get a new toaster? Nah, I'm calling it fixing by over-complication, a speciality of mine

**Comment by brentru** [comment]
> should I add the types to sensor repo even though they stretch the definition of SI units?

Yes, and to the I2C driver file(s) via your existing SEN55 PR

**Comment by tyeth** [comment]
Updated #105 and the sensors repo. The driver is done too, think I got protobuffer updated, but there's probably something I missed. Mostly I think the new component sensor types wont exist for a while so checks will fail.
 Also just curious if the dev component _Could_ exist with voc-index type and not break the matrix if I hadn't yet added voc-index methods to the i2c driver.

Side note, the gas resistance for BME680 presents an index too, and meant to represent VOC or Air quality index, but I'm not 200% on what else needs changing in backend etc so leaving that for now. It's setup to return resistance for now. I got confused and thought that was the true voc sensor with parts per billion, nevermind https://github.com/tyeth/Adafruit_Wippersnapper_Arduino/blob/827692822570265fba2d16bb50366fb7983d0df5/src/components/i2c/drivers/WipperSnapper_I2C_Driver_BME680.h#L155-L170
<img width="323" alt="image" src="https://user-images.githubusercontent.com/6692083/207980040-b39fea37-88aa-4350-ae05-08e46e557fc4.png">

**Comment by brentru** [comment]
> Updated https://github.com/adafruit/Wippersnapper_Components/pull/105 and the sensors repo.

Sweet, working on reviewing everything!

> Side note, the gas resistance for BME680 presents an index too, 

Could you split this into a new issue so we can properly track and address it?
