### ISSUE TITLE
[REQ] Component Request: HTS221 Humidity Sensor

### ISSUE THREAD

**Issue by whatisbyandby** [adafruit/Wippersnapper_Components#130]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
HTS221 Humidity Sensor

**What type of component is this (i.e.: Pin, I2C)?**
I2C

**Product URL or Datasheet**
Product URL: [https://www.adafruit.com/product/4535](https://www.adafruit.com/product/4535)

**Additional context**
This sensor can also measure ambient temperature

**Comment by whatisbyandby** [comment]
I'm working on the component definition, and should have a PR ready in the next day or so.

**Comment by tyeth** [comment]
Thanks @whatisbyandby ❤️
