### ISSUE TITLE
Adafruit STEMMA Soil Sensor - I2C Capacitive Moisture Sensor

### ISSUE THREAD

**Issue by brentru** [adafruit/Wippersnapper_Components#14]
https://www.adafruit.com/product/4026

**Comment by marcuswu** [comment]
I looked into adding this driver. I'm not sure how to handle the capacitive moisture sensor. WipperSnapper utilizes [sensors_event_t](https://github.com/adafruit/Adafruit_Sensor#sensor-dataevents-sensors_event_t) from the [Adafruit_Sensor](https://github.com/adafruit/Adafruit_Sensor) project which ensures all sensor data is normalized to SI units.

The SI unit for capacitance is the Farad, but it's unknown how to correlate the sensor's output range to a unit of measurement. The most detail I found on its output is from the [learn.adafruit page](https://learn.adafruit.com/adafruit-stemma-soil-sensor-i2c-capacitive-moisture-sensor/overview), "... [the sensor] will give you a reading ranging from about 200 (very dry) to 2000 (very wet)."

Without any characterization of the sensor or a project direction for writing drivers for non-unified sensor data, I'm afraid this will need to wait.

**Comment by brentru** [comment]
@marcuswu  Yeah this is a bit of an odd sensor for the reasons you listed.

WipperSnapper may need a `capacitive moisture` data type to correlate the reading. However, we could [possibly use a raw sensor type](https://github.com/adafruit/Wippersnapper_Protobuf/blob/master/proto/wippersnapper/i2c/v1/i2c.proto#L171) as well. 

You could try packing the data into sensors_event_t's `data` float (we do this for a few of the CO2 drivers that lack a property within `sensors_event_t`) and sending it to wipperSnapper as `SENSOR_TYPE_RAW`.

**Comment by marcuswu** [comment]
Awesome, I missed the raw sensor type. I'll take a look.

**Comment by marcuswu** [comment]
I added [Adafruit_Wippersnapper_Arduino PR #303](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/303). I guess there'd be a PR here too, but I left this one as a draft because I'm not able to test that code right now as my hardware is in use in a hard to reach spot now.

**Comment by brentru** [comment]
@marcuswu  Could you checkout a PR for the stemma soil sensor's component definition within **this** repository? I'll be able to test this on hardware for you.
