### ISSUE TITLE
[REQ] Component Request: Sensirion SHT40 Temperature & Humidity Sensor

### ISSUE THREAD

**Issue by brentru** [adafruit/Wippersnapper_Components#17]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
Sensirion SHT40 Temperature & Humidity Sensor

**What type of component is this (i.e.: Pin, I2C)?**
I2C

**Product URL or Datasheet**
https://www.adafruit.com/product/4885

**Additional context**
N/A

**Comment by TheGodMotherG** [comment]
Yes please it the best sensor on the market please add support

**Comment by TheGodMotherG** [comment]
I did my best to add it myself but am getting an error

**Comment by TheGodMotherG** [comment]
Ok i got it to verify the code I wrote for this sensor just waiting for it to be approved. fingers crossed

https://github.com/adafruit/Wippersnapper_Components/pull/49

 in case you wanted to take a look

**Comment by brentru** [comment]
Thanks for adding this. I took a look, let's continue this convo on #49.

**Comment by brentru** [comment]
@TheGodMotherG Support for SHT4x-family of sensors has been added in WipperSnapper firmware beta 43

https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/releases/tag/1.0.0-beta.43

**Comment by brentru** [comment]
@TheGodMotherG  I used your component and some of the driver work, very.

**Comment by TheGodMotherG** [comment]
Thank you again already using it and ordering more sensors!

How much time do you assume it took you to edit my stuff to get it to work?
I’m just genuinely curious how close I got.

Also

Any chance to get it to work in F or a document you can point me to to get
it to work that way?

I get the whole world uses C and I do agree we should be on the metric
system. But It would be great to have a C or F feature

**Comment by brentru** [comment]
>  How much time do you assume it took you to edit my stuff to get it to work?. I’m just genuinely curious how close I got.

Probably 15min incl. testing, very close!

> Any chance to get it to work in F or a document you can point me to to get it to work that way?

Does it not show up under "Edit Component"? Could you link me to the component definition for this sensor?
