### ISSUE TITLE
[REQ] Component Request: BH1750 Light Sensor

### ISSUE THREAD

**Issue by brentru** [adafruit/Wippersnapper_Components#19]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
BH1750 Light Sensor

**What type of component is this (i.e.: Pin, I2C)?**
I2C

**Product URL or Datasheet**
https://www.adafruit.com/product/4681

**Additional context**
N/A

**Comment by brentru** [comment]
This issue is marked for [Hacktoberfest 2022](https://hacktoberfest.com/). If you are participating in Hacktoberfest and want to take on this issue, please first **fully read through** the guide for ["How to add a new component to Adafruit IO WipperSnapper"](https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper).

For I2C Components to work, please note that you are required to add **both** an I2C component definition ([see this guide page for more information](https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper/adding-an-i2c-component)) to this repository **and** an I2C component driver ([see this guide page for more information](https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper/adding-an-i2c-component-driver)) to [the WipperSnapper Firmware Repository](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/).

If you have any questions, comments, or concerns, please feel free to tag me in the comments here, or in your pull request for review. 

Happy Hackin'!

**Comment by whatisbyandby** [comment]
I'm going to plan to pick up this component. I'll open a PR for the JSON shortly.

**Comment by tyeth** [comment]
Thanks @whatisbyandby for your contributions!
