### ISSUE TITLE
[REQ] Component Request: MCP9601 Thermocouple

### ISSUE THREAD

**Issue by brentru** [adafruit/Wippersnapper_Components#20]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
MCP9601 (MCP96L01) I2C Thermocouple Amplifier

**What type of component is this (i.e.: Pin, I2C)?**
I2C

**Product URL or Datasheet**
https://www.adafruit.com/product/5165

**Additional context**
n/a

**Comment by brentru** [comment]
Addressing in https://github.com/adafruit/Wippersnapper_Components/pull/29

**Comment by brentru** [comment]
Addressed in #29

**Comment by tyeth** [comment]
This component has issues and is not currently planned for support, due to failing to initialise after being i2c scanned. 
Hotplugging the device after scanning was deemed unacceptable. 

Maybe revisit after python version of wippersnapper lands
