### ISSUE TITLE
[REQ] Component Request: PMSA0031

### ISSUE THREAD

**Issue by brooksdr** [adafruit/Wippersnapper_Components#24]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
The full name of the specific component. PMSA0031 Air Quality Breakout

**What type of component is this (i.e.: Pin, I2C)?** It has an I2C interface
Add any other context about the component request here.

**Product URL or Datasheet**
Add a link to the product's URL or datasheet here. https://www.adafruit.com/product/4632

**Additional context**
Add any other context about the component request here. Because this device includes a small fan to drive air through the measuring chamber, it requires a support board that will provide the necessary power (a little less than 100 mA for the fan?) The fan is 5V but the cited board has a step-up circuit for use with 3.3V boards.

**Comment by brentru** [comment]
Hi! We've added support for the PMSA003i Air Quality Breakout in WipperSnapper Beta 44.

https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/releases/tag/1.0.0-beta.44
