### ISSUE TITLE
[REQ] Component Request: DS18B20-compatible temperature sensors

### ISSUE THREAD

**Issue by brentru** [adafruit/Wippersnapper_Components#36]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
Waterproof 1-Wire DS18B20 Compatible Digital temperature sensor

**What type of component is this (i.e.: Pin, I2C)?**
1-Wire

**Product URL or Datasheet**
https://www.adafruit.com/product/381
https://www.adafruit.com/product/642
https://www.adafruit.com/product/374

**Additional context**
Requires https://github.com/adafruit/Wippersnapper_Protobuf/issues/89 to be implemented first.

**Comment by brentru** [comment]
https://github.com/adafruit/Wippersnapper_Components/pull/43

**Comment by ladyada** [comment]
i think this can be closed :)

**Comment by brentru** [comment]
Closing, supported by the latest WipperSnapper firmware!
