### ISSUE TITLE
[REQ] Component Request: Adafruit SCD-30

### ISSUE THREAD

**Issue by jwcooper** [adafruit/Wippersnapper_Components#38]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
Adafruit SCD-30 - NDIR CO2 Temperature and Humidity Sensor

**What type of component is this (i.e.: Pin, I2C)?**
I2C

**Product URL or Datasheet**
[SCD-30 product page](https://www.adafruit.com/product/4867)
optionally:
[SCD-40 product page](https://www.adafruit.com/product/5187)
[SCD-41product page](https://www.adafruit.com/product/5190)

**Additional context**
Via support request

Might also be able to do the scd-40 and scd-41 at the same time.

**Comment by ckostovny** [comment]
I added an i2c component for the SCD-30, it appears to work.

**Comment by brentru** [comment]
Added by https://github.com/adafruit/Wippersnapper_Components/pull/39

@jwcooper  Are you able to test SCD40/41? Unsure if this PR will work for all 3, I think I want 3 sep. component icons though...
