### ISSUE TITLE
NeoPixel component request

### ISSUE THREAD

**Issue by cjdaly** [adafruit/Wippersnapper_Components#5]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**

Support for NeoPixel strands.

**Product URL or Datasheet**

Any NeoPixel strands wired to WipperSnapper boards such that they could be controlled via CircuitPython or Arduino. 

**Additional context**

I connected 2 [NeoKey](https://www.adafruit.com/product/4978) breakouts to a FunHouse board and wrote a CircuitPython script to read the key presses and change the NeoKey NeoPixel colors.   Later I tried this [same setup](https://compucanvas.substack.com/p/lights-camera-action) with WipperSnapper.   I'm able to read the key presses using the info from the [digital inputs guide](https://learn.adafruit.com/digital-inputs-with-adafruit-io-wippersnapper).  But I don't see any way of controlling the NeoPixels.

**Comment by brentru** [comment]
Resolved via https://github.com/adafruit/Wippersnapper_Components/pull/117

WipperSnapper currently ships with NeoPixels as of Beta 59 and up!
