### ISSUE TITLE
[REQ] Component Request: LTR390 UV Light Sensor

### ISSUE THREAD

**Issue by ripexz** [adafruit/Wippersnapper_Components#58]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
Adafruit LTR390 UV Light Sensor - STEMMA QT / Qwiic

**What type of component is this (i.e.: Pin, I2C)?**
I2C

**Product URL or Datasheet**
https://www.adafruit.com/product/4831

**Additional context**
Arguably SI1145 is also an option though it's not true UV. GUVA-S12SD would be nice also/instead, though that's entirely analog (I might get around to setting up PR for that one myself 😅)

**Comment by tyeth** [comment]
Closed by #196

@ripexz this component has been added, please try the latest release of WipperSnapper, or wait until next week when we have a new release again.
