### ISSUE TITLE
dotstar component request

### ISSUE THREAD

**Issue by cjdaly** [adafruit/Wippersnapper_Components#6]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**

DotStar chains, like the 5 DotStars on the FunHouse board

**Product URL or Datasheet**

FunHouse:  https://www.adafruit.com/product/4985

**Additional context**

I tried WipperSnapper recently for the first time with a FunHouse.   I got it connected (so easy!), and was able to add a component for the red LED and control that (easy!).  But the next thing I wanted to do is set the 5 DotStars and I could not see any way to do that.

**Comment by brentru** [comment]
Resolved via https://github.com/adafruit/Wippersnapper_Components/pull/117

WipperSnapper currently ships with DotStar as of Beta 59 and up!
