### ISSUE TITLE
[REQ] Component Request: SHT30/31/35 and maybe 3C/3x

### ISSUE THREAD

**Issue by tyeth** [adafruit/Wippersnapper_Components#72]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
Sensiron SHT35 and SHT30

**What type of component is this (i.e.: Pin, I2C)?**
I2C

**Product URL or Datasheet**
https://www.adafruit.com/product/2857
Mine is actually not this exact model, I have 30's and 35's also with address and alert pins. They (SHT30/31/35) all speak the same as far as I know.

**Additional context**
Tried using the SHT40 component, and it shows up as the default i2c address is the same, but the values are not retrieved.
It would also be a welcome luxury to add the additional i2c addresses to this (SHT40/3x) and other components, half mentioned as a question in this issue  https://github.com/adafruit/Wippersnapper_Boards/issues/70

**Comment by tyeth** [comment]
Yes I believe the 30/31/35 (ignoring -D suffix) are all the same, only the 3C may be different. I was going to try the adafruit 31-d later, but yes that was exactly my thinking. Just looking at adding the Si7021 for now so not instantly testable sorry.

**Comment by tyeth** [comment]
@brentru It's interesting, last night took a look at arduino-sht (sensiron library for all the sht sensors, and mostly the same, but 3x/4x have extra options for high sensitivity so the init code varies a bit (it safely returns false if any option unsupported). 

 Currently for the 4x we are using the "sensirion sht4x i2c" arduino library, not the catch all sensirion "arduino-sht". We can use the arduino-sht and get access to a few extra sensors for very little. I suggest maybe adding components for known adafruit SHT boards like SHT31-D and SHTC3, with desired resolution/sampling, and then maybe having a Sensirion SHT-Series (auto) component that could support the full list but only default (automatic) initialisation (library warns if mixed models on bus then must specify model). Alternatively do I just add the 3X + C3 + 85 as individual components?

full list used if specifying sensor: https://github.com/Sensirion/arduino-sht/blob/master/SHTSensor.h#L51
(SHT3X, SHT85, SHTC1, SHTC3, SHTW1, SHTW2, SHT4X)

Difference in init code:
sht3x https://github.com/Sensirion/arduino-sht/blob/master/SHTSensor.cpp#L164
sht4x https://github.com/Sensirion/arduino-sht/blob/master/SHTSensor.cpp#L213

I also wondered about the option to have an input for the sensors, because they (and the Si7021) support turning on an internal heater, which would be useful to very few I'd imagine, but is right up there for me due to outdoor freezing / condensing humidity being a concern. Not worth adding to these components, but wondered if components can have inputs, like heater status, or sampling / Sensitivity option in a dropdown for example.

**Comment by brentru** [comment]
> arduino-sht

I don't mind combining the drivers and relying on one dependency for them! 

> Alternatively do I just add the 3X + C3 + 85 as individual components?

Add them as individual components to the WipperSnapper Components repository. I like the idea of having one SHT component driver in WipperSnapper Arduino, though the code which handles selecting which driver to use may need to be modified (possibly this would be within the constructor for each i2c driver). From a development perspective, I'd suggest adding SHT3x, SHTC3 to WipperSnapper Arduino, then seeing what can be made more generic for the "auto" SHTx driver.

> I also wondered about the option to have an input for the sensors, because they (and the Si7021) support turning on an internal heater, which would be useful to very few I'd imagine

Adding extra parameters for I2C componentsinitialization, such as options to turn on/off heaters or sampling status, is something @lorennorman  and I have discussed but it's likely more medium-term as we'll need to modify/add to the existing protobuffer communication messages for i2c.

**Comment by tyeth** [comment]
This has been submitted as #77, but includes a rename of the SHT40 to lowercase which we want to be sure isn't damaging. The SHTC1/2/3 and SHTW1/2/3 will be added in a separate pull request. Adafruit offer the C3, which makes sense to add (as SHTC3 or SHTC3/1 or SHTCx or SHTCX?), but there may instead/as-well be a new component that runs the Auto Detection routine by sensirion, I suggest SHTxx, it doesn't support detecting a second device on the same bus so maybe less useful for some as it always finds first device in this order :
    SHT3X,
    SHT85,
    SHT3X_ALT,  /** SHT3x-DIS with ADDR (sensor pin 2) connected to VDD */
    SHTC1,
    SHTC3,
    SHTW1,
    SHTW2,
    SHT4X

**Comment by brentru** [comment]
With WipperSnapper, we currently prefer to have the user specify the sensor they need in the component picker rather than automatically detecting it. It'll be more code to have a SHT3x, SHT85... sensor class, but, it'll always initialize the correct sensor for the correct sensor type selected by a user.

**Comment by tyeth** [comment]
So if we go with separate components, do we refactor the SHT4x file to a generic on and pass in the sensor type from the i2c.cpp file, it would mean importing shtsensor.h to i2c.cpp too... I'm guessing for now the duplication is preferred with separate classes and no additional import in the i2c.cpp file...

**Comment by tyeth** [comment]
Will add separate classes for each. Grab yourself a C3 too please :) https://www.adafruit.com/product/4636

**Comment by tyeth** [comment]
Happy this works and is merged now, so closing as completed. 
Available in upcoming release v54 or built from source immediately
