### ISSUE TITLE
Support °F as well as °C

### ISSUE THREAD

**Issue by brentru** [adafruit/Wippersnapper_Components#74]
Per https://github.com/adafruit/Wippersnapper_Protobuf/issues/109, we'd like components to be able to support a selectable ambient or object temperature of °F. This would be considered as a new "unit".

**Comment by tyeth** [comment]
I think we need to add some calculated fields/outputs per [sensor type](https://github.com/adafruit/Wippersnapper_Components#i2c-sensor-types). That's what *F is, so then any existing temp sensor gets *F, and a fusion device (like one providing temp+humidty) can provide VPD(vapour pressure deficit) / Dew-point solving #71 and other future needs based off of calculations from the fusion sensor/device. I think custom options at the are probably too much work, as you can take the data if needed out of adafruit IO, but common needs for the sensor / data type make sense.

**Comment by brentru** [comment]
@tyeth That's what we're doing in https://github.com/adafruit/Wippersnapper_Components/pull/75.

VPD is not on my high priority list right now, but, we can add additional types for VPD/sensor fusion in the future, in the same method that we're adding *F.

**Comment by tyeth** [comment]
Thank you, I shall follow it keenly :) I care little right now for VPD, but it's on my greenhouse priority list (way down there)

**Comment by brentru** [comment]
Resolved in https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/324, please use Beta 51 and up for this functionality to appear!
