### ISSUE TITLE
[REQ] Component Request: ENS160 MOX Gas Sensor

### ISSUE THREAD

**Issue by brentru** [adafruit/Wippersnapper_Components#80]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
Adafruit ENS160 MOX Gas Sensor - Sciosense CCS811 Upgrade - STEMMA QT / Qwiic

**What type of component is this (i.e.: Pin, I2C)?**
I2C

**Product URL or Datasheet**
https://www.adafruit.com/product/5606

**Additional context**
The ENS160 is the replacement for the [popular, but now-discontinued CCS811](https://www.sciosense.com/products/environmental-sensors/ccs811/). It has similar functionality but does require all new driver code

**Comment by tyeth** [comment]
This component has now been added! It's available in release v1.0.0.beta-72
