### ISSUE TITLE
<Docs> Adding Contributing Guidelines

### ISSUE THREAD

**Issue by krupalitrivedi** [adafruit/Wippersnapper_Components#83]
Hello!

As of now, there are no contributing guidelines present in the project which are essential for everyone who wishes to contribute to the project. If the maintainers and owners are okay with it, I would like to create basic contributing guidelines files, in which further information can be added as needed!

Would love to work on it and probably submit it during the first week of hactoberfest if possible!

Thank you!

**Comment by brentru** [comment]
@krupalitrivedi We do not have contributing guidelines for this repository, however, we have [a code of conduct](https://github.com/adafruit/Wippersnapper_Components/blob/main/CODE_OF_CONDUCT.md) to adhere to and a guide for adding components with detailed instructions here: https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper
