### ISSUE TITLE
[REQ] Component Request: VEML7700 light sensor

### ISSUE THREAD

**Issue by tyeth** [adafruit/Wippersnapper_Components#89]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
Adafruit Right Angle VEML7700 Lux Sensor - I2C Light Sensor - STEMMA QT / Qwiic

**What type of component is this (i.e.: Pin, I2C)?**
I2C

**Product URL or Datasheet**
https://www.adafruit.com/product/5378

**Additional context**
I want to add this after picking one up this week, but it has three subcomponents as I see it, Lux, Light_ADC and White_ADC. I've read the adafruit libraries for c +py and it seems sensible to return the auto_Lux version rather than pick a specific gain+interval of measurement.  
https://github.com/adafruit/Adafruit_VEML7700/blob/master/Adafruit_VEML7700.cpp#L398

 I wondered what sensorTypes to use. My initial intention was to use "light" listed on the readme, but the components/sensorTypes.json lists a Light (Lux) sensorType of "lux" which is now the obvious choice, or am I mistaken? I also was unsure on what to use for the raw ALS/ADC values and assume "raw" or "unspecified" sensorTypes for those two subcomponents. 
  Does that sound about right?

**Comment by brentru** [comment]
> I've read the adafruit libraries for c +py and it seems sensible to return the auto_Lux version rather than pick a specific gain+interval of measurement.

This is something we're looking into and why few light sensors have been added so far. We'd ideally like to do auto-ranging for light sensor drivers.
