### ISSUE TITLE
[REQ] Component Request: INA219 High Side DC Current Sensor

### ISSUE THREAD

**Issue by brentru** [adafruit/Wippersnapper_Components#90]
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
* INA219 High Side DC Current Sensor Breakout - 26V ±3.2A Max - STEMMA QT
* Adafruit INA219 FeatherWing

**What type of component is this (i.e.: Pin, I2C)?**
I2C

**Product URL or Datasheet**
https://www.adafruit.com/product/904
https://www.adafruit.com/product/3650

**Comment by morwic** [comment]
Please by the powers of the great Ada \o/ \0/ \O/ \o/ Please let this request happen as fast as you can get it done <3

**Comment by tyeth** [comment]
@morwic this component has now been added! It's available in release v1.0.0.beta-72
